# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:30'
      timezone: 'Etc/GMT'
    target-branch: 'dev'
    pull-request-branch-name:
      separator: '-'

  # Minor updates to npm production dependencies daily
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:45'
      timezone: 'Etc/GMT'
    versioning-strategy: lockfile-only
    target-branch: 'dev'
    pull-request-branch-name:
      separator: '-'
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
