name: Audit dependencies

on: push

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Setup Node.js
        uses: actions/setup-node@v4 # https://github.com/actions/setup-node
        with:
          node-version: '20.x'
          cache: 'npm'
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: true

      - run: npm audit --package-lock-only --production --audit-level=high
