name: Audit dependencies

on: push

jobs:
  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v5 # https://github.com/actions/checkout
      - name: Setup Node.js
        uses: actions/setup-node@v6 # https://github.com/actions/setup-node
        with:
          node-version: '24.x'
          cache: 'npm'
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: true
      # Audit prod dependencies (there are none and hopefully never will be any :P)
      - run: npm audit --package-lock-only --omit=dev --audit-level=high
