name: Automatic-node-tests

on: push

jobs:
  test-node-versions:
    name: Test with maintained Node.js versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4 # https://github.com/actions/setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: true
      - run: npm i
      - run: npm test

  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Setup Node.js
        uses: actions/setup-node@v4 # https://github.com/actions/setup-node
        with:
          node-version: '20.x'
          cache: 'npm'
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: true
      - run: npm i
      - run: npm run lint

  audit:
    name: Audit dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4 # https://github.com/actions/checkout
      - name: Setup Node.js
        uses: actions/setup-node@v4 # https://github.com/actions/setup-node
        with:
          node-version: '20.x'
          cache: 'npm'
        env:
          NPM_CONFIG_IGNORE_SCRIPTS: true

      - run: npm audit --package-lock-only --production --audit-level=high
